/**
 * certificateService.js — MOCK.
 * "Certificate document stored off-chain." "Document hash generated by backend."
 */
import { generateCertificateId } from "../utils/ids.js";

export function issueCertificate({ batchId, labId, testDate, result, verifierId, fileName }) {
  return {
    certificateId: generateCertificateId(),
    batchId,
    labId,
    testDate,
    issueDate: new Date().toISOString().slice(0, 10),
    result,
    verifierId,
    fileName,
    uploaded: true,
  };
}
