import React from "react";
import { ShieldCheck } from "lucide-react";
import { formatDateTime } from "../utils/format.js";

/**
 * Section 25 — dedicated visual panel that clearly labels every
 * blockchain-related field as backend-generated / pending, never
 * fabricating a hash, signature, or transaction reference.
 */
export default function BlockchainProofCard({ event }) {
  if (!event) {
    return (
      <div className="bg-white rounded-2xl border border-[#ECE6D6] shadow-sm p-5 text-sm text-[#8A9086]">
        No provenance event selected yet.
      </div>
    );
  }
  const row = (label, value) => (
    <div className="flex justify-between py-1.5 border-b border-[#ECE6D6] last:border-none text-[13px]">
      <span className="text-[#8A9086]">{label}</span>
      <span className="font-semibold text-right">{value}</span>
    </div>
  );
  return (
    <div className="bg-bc-deep-green rounded-2xl p-5 text-white">
      <div className="flex items-center gap-2 font-display text-lg mb-1">
        <ShieldCheck size={18} /> Blockchain Proof
      </div>
      <div className="inline-block bg-white/15 text-white text-xs font-bold px-2.5 py-1 rounded-full mb-3">
        Status: Integration Pending
      </div>
      <div className="bg-white text-bc-dark rounded-xl p-4">
        {row("Event ID", event.eventId)}
        {row("Batch ID", event.batchId)}
        {row("Event Type", event.eventType.replaceAll("_", " "))}
        {row("Actor ID", event.actorId)}
        {row("Occurred At", formatDateTime(event.occurredAt))}
        {row("Recorded At", formatDateTime(event.recordedAt))}
        {row("Payload Hash", "Generated by Backend")}
        {row("Previous Event Hash", "Linked by Backend")}
        {row("Digital Signature", "Generated by Authorized Backend/Wallet")}
        {row("Blockchain Transaction", "Pending")}
      </div>
    </div>
  );
}
