import React from "react";
import { Check, Upload } from "lucide-react";
import StatusBadge from "./StatusBadge.jsx";

export default function CertificateCard({ cert, onUpload }) {
  return (
    <div className="bg-white rounded-2xl border border-[#ECE6D6] shadow-sm p-5">
      <div className="flex justify-between flex-wrap gap-2">
        <div>
          <div className="text-xs text-[#8A9086]">Certificate ID</div>
          <div className="font-bold font-display text-bc-deep-green">{cert.certificateId}</div>
        </div>
        <StatusBadge status={cert.result} tone={cert.result === "PASS" ? "success" : "critical"} />
      </div>
      <div className="text-xs text-[#8A9086] mt-2">
        Batch {cert.batchId} · Laboratory {cert.labId} · Issued {cert.issueDate}
      </div>
      {cert.uploaded ? (
        <div className="flex items-center gap-2 mt-3 text-sm text-bc-success font-semibold">
          <Check size={15} /> {cert.fileName} uploaded
          <span className="text-bc-deep-green cursor-pointer ml-1">Preview</span>
        </div>
      ) : (
        <button
          onClick={onUpload}
          className="mt-3 flex items-center gap-2 text-sm font-bold border border-bc-deep-green text-bc-deep-green rounded-xl px-4 py-2 hover:bg-bc-light-green transition-colors"
        >
          <Upload size={15} /> Upload Certificate
        </button>
      )}
      <div className="text-[11px] text-[#B08900] bg-bc-light-honey rounded-lg px-2.5 py-1.5 mt-3 inline-block">
        Certificate document stored off-chain · Document hash generated by backend
      </div>
    </div>
  );
}
