import React, { useState } from "react";
import { useSearchParams } from "react-router-dom";
import PageHeader from "../../components/PageHeader.jsx";
import UploadBox from "../../components/UploadBox.jsx";
import CertificateCard from "../../components/CertificateCard.jsx";
import EmptyState from "../../components/EmptyState.jsx";
import { useApp } from "../../hooks/useApp.js";
import { validateCertificateIssue } from "../../utils/validators.js";

export default function Certificates() {
  const { batches, certificates, issueCertificate } = useApp();
  const [params] = useSearchParams();
  const [pendingFor, setPendingFor] = useState(params.get("batchId") || "");
  const [errors, setErrors] = useState({});

  // Batches that passed analysis but have no certificate yet.
  const eligible = batches.filter((b) => b.stage >= 5 && b.certStatus !== "CERTIFIED");

  const upload = (batch, fileNames) => {
    const values = { certificateId: "auto", file: fileNames[0] };
    const { valid, errors: errs } = validateCertificateIssue(values);
    setErrors((p) => ({ ...p, [batch.batchId]: errs.file }));
    if (!valid) return;
    issueCertificate({ batchId: batch.batchId, testDate: batch.harvestDate, result: batch.testStatus, fileName: fileNames[0] });
    setPendingFor("");
  };

  return (
    <div>
      <PageHeader title="Certificates" sub="Certificate documents are stored off-chain; the hash will be generated by the backend." />

      {eligible.length > 0 && (
        <div className="mb-7">
          <div className="font-bold text-sm mb-2.5">Ready to Certify</div>
          <div className="flex flex-col gap-3.5">
            {eligible.map((b) => (
              <div key={b.batchId} className="bg-white rounded-2xl border border-[#ECE6D6] shadow-sm p-5">
                <div className="font-bold font-display text-bc-deep-green">{b.batchId}</div>
                <div className="text-xs text-[#8A9086] mb-3">Test result: {b.testStatus}</div>
                <UploadBox label="Upload original laboratory report" onFiles={(names) => upload(b, names)} />
                {errors[b.batchId] && <div className="text-bc-critical text-xs mt-2">{errors[b.batchId]}</div>}
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="font-bold text-sm mb-2.5">Issued Certificates</div>
      <div className="flex flex-col gap-3.5">
        {certificates.length === 0 ? <EmptyState title="No certificates issued yet" /> : certificates.map((c) => <CertificateCard key={c.certificateId} cert={c} />)}
      </div>
    </div>
  );
}
